name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  serviceJsonStr:
    description: 'json string that stores service information'
    required: false
    default: ''
  serviceJsonFilePath:
    description: 'the local address of the json file that stores service information'
    required: false
    default: ''
  languageTypeField:
    description: 'the field about language env type'
    required: true
    default: 'languageEnvType'
  languageVersionField:
    description: 'the field about language env version'
    required: true
    default: 'languageEnvVersion'

# Define your outputs here.
outputs:
  languageEnv:
    description: 'all language env info in services'

runs:
  using: node20
  main: dist/index.js
