name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: storage service
        run: |
          echo "[{\"name\":\"matrix-cloud-blockchain-syncer\",\"type\":\"service\",\"language\":[\"java\"],\"languageEnvType\":\"java\",\"languageEnvVersion\":\"11\",\"report\":\"https\",\"projectPath\":[\"matrix-cloud-blockchain-syncer\"],\"_\":null,\"coverage\":0},{\"name\":\"matrix-cloud-flow-service-grpc\",\"type\":\"library\",\"language\":[\"golang\"],\"languageEnvType\":\"golang\",\"languageEnvVersion\":\"1.20\",\"report\":\"\",\"projectPath\":[\"matrix-cloud-flow-service-grpc\"],\"_\":null,\"coverage\":0}]" > /tmp/service.json
          cat /tmp/service.json
      
      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          serviceJsonFilePath: "service.json"
          languageTypeField: languageEnvType
          languageVersionField: languageEnvVersion

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.languageEnv }}"
